######################################################################
#
# File name : tb_hdmi_colorbar_top_wave.do
# Created on: Tue Apr 30 20:26:55 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
