######################################################################
#
# File name : tb_hdmi_colorbar_top_compile.do
# Created on: Wed May 01 09:53:40 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../med_filter.srcs/sources_1/ip/clk_wiz_0" \
"../../../../med_filter.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../med_filter.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../med_filter.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../../src/Matrix_Generate_3X3_8Bit.v" \
"../../../../../../src/Video_Image_Processor.v" \
"../../../../../../src/asyn_rst_syn.v" \
"../../../../../../src/dvi_encoder.v" \
"../../../../../../src/dvi_transmitter_top.v" \
"../../../../../../src/hdmi_colorbar_top.v" \
"../../../../../../src/median_filter_proc.v" \
"../../../../../../src/serializer_10_to_1.v" \
"../../../../../../src/sync_fifo.v" \
"../../../../../../src/video_display.v" \
"../../../../../../src/video_driver.v" \
"../../../../../../sim/tb_src/tb_hdmi_colorbar_top.v" \


# compile glbl module
C:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

