######################################################################
#
# File name : tb_hdmi_colorbar_top_simulate.do
# Created on: Wed May 01 09:53:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_1 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_hdmi_colorbar_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_hdmi_colorbar_top_wave.do}

view wave
view structure
view signals

do {tb_hdmi_colorbar_top.udo}

run 1000ns
