set_property SRC_FILE_INFO {cfile:C:/code/zynq_pri/zynq_study/ip_2port_ram/rtl/syn/script/top.xdc rfile:../../../script/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports sys_rst_n]
