# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Common 17-41} -limit 10000000

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param general.maxThreads 8
  set_param simulator.modelsimInstallPath C:/modeltech64_10.6d/win64
  create_project -in_memory -part xc7z020clg400-2
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir C:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.cache/wt [current_project]
  set_property parent.project_path C:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.xpr [current_project]
  set_property ip_output_repo C:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
  add_files -quiet C:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.runs/synth_1/DDS_test.dcp
  read_ip -quiet c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_triangular/rom_triangular.xci
  read_ip -quiet c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_square/rom_square.xci
  read_ip -quiet c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_sine/rom_sine.xci
  link_design -top DDS_test -part xc7z020clg400-2
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force DDS_test_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file DDS_test_drc_opted.rpt -pb DDS_test_drc_opted.pb -rpx DDS_test_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  implement_debug_core 
  place_design 
  write_checkpoint -force DDS_test_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file DDS_test_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file DDS_test_utilization_placed.rpt -pb DDS_test_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file DDS_test_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force DDS_test_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file DDS_test_drc_routed.rpt -pb DDS_test_drc_routed.pb -rpx DDS_test_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file DDS_test_methodology_drc_routed.rpt -pb DDS_test_methodology_drc_routed.pb -rpx DDS_test_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file DDS_test_power_routed.rpt -pb DDS_test_power_summary_routed.pb -rpx DDS_test_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file DDS_test_route_status.rpt -pb DDS_test_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file DDS_test_timing_summary_routed.rpt -rpx DDS_test_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file DDS_test_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file DDS_test_clock_utilization_routed.rpt"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force DDS_test_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

