# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_square/rom_square.xci
# IP: The module: 'rom_square' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_square/rom_square_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_square'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_square/rom_square.xci
# IP: The module: 'rom_square' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_square/rom_square_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_square'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
