######################################################################
#
# File name : tb_hdmi_colorbar_top_compile.do
# Created on: Sun Apr 14 10:58:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../top.srcs/sources_1/ip/clk_wiz_0" \
"../../../../top.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../top.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../top.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../src/asyn_rst_syn.v" \
"../../../../../src/contrast_adjust.v" \
"../../../../../src/dvi_encoder.v" \
"../../../../../src/dvi_transmitter_top.v" \
"../../../../../src/fifo.v" \
"../../../../../src/hdmi_colorbar_top.v" \
"../../../../../src/serializer_10_to_1.v" \
"../../../../../src/video_display.v" \
"../../../../../src/video_driver.v" \
"../../../../../sim/tb_src/tb_hdmi_colorbar_top.v" \


# compile glbl module
C:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

