######################################################################
#
# File name : tb_hdmi_colorbar_top_wave.do
# Created on: Sat Apr 13 21:07:15 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
