######################################################################
#
# File name : tb_ip_2port_ram_compile.do
# Created on: Tue Apr 02 15:40:20 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../top.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../top.srcs/sources_1/ip/ila_0/sim/ila_0.v" \
"../../../../../src/ram_rd.v" \
"../../../../../src/ram_wr.v" \
"../../../../../src/ip_2port_ram.v" \
"../../../../../sim/tb/tb_ip_2port_ram.v" \


# compile glbl module
C:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

