######################################################################
#
# File name : tb_ip_2port_ram.udo
# Created on: Tue Apr 02 15:22:48 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
