######################################################################
#
# File name : DDS_test_tb_simulate.do
# Created on: Sat Jul 20 18:00:28 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L blk_mem_gen_v8_4_1 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.DDS_test_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {DDS_test_tb_wave.do}

view wave
view structure
view signals

do {DDS_test_tb.udo}

run 1000ns
