######################################################################
#
# File name : DDS_test_tb.udo
# Created on: Sat Jul 20 18:00:28 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
