######################################################################
#
# File name : DDS_test_tb_compile.do
# Created on: Sat Jul 20 18:00:24 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xpm
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/blk_mem_gen_v8_4_1

C:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
C:\\modeltech64_10.6d\\win64\\vmap xpm modelsim_lib/msim/xpm
C:\\modeltech64_10.6d\\win64\\vmap blk_mem_gen_v8_4_1 modelsim_lib/msim/blk_mem_gen_v8_4_1

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

C:\\modeltech64_10.6d\\win64\\vcom -64 -93 -work xpm  \
"C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work blk_mem_gen_v8_4_1  \
"../../../../DDS_test.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../DDS_test.srcs/sources_1/ip/rom_triangular/sim/rom_triangular.v" \
"../../../../DDS_test.srcs/sources_1/ip/rom_square/sim/rom_square.v" \
"../../../../DDS_test.srcs/sources_1/ip/rom_sine/sim/rom_sine.v" \
"../../../../../../src/DDS_test.v" \
"../../../../../../sim/tb_src/DDS_test_tb.v" \

# compile glbl module
C:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

