######################################################################
#
# File name : DDS_test_tb_wave.do
# Created on: Sat Jul 20 18:00:28 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
