# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
set_param simulator.modelsimInstallPath C:/modeltech64_10.6d/win64
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.cache/wt [current_project]
set_property parent.project_path C:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/code/zynq_pri/zynq_study/DDS_test/alg/tri_wave.coe
add_files c:/code/zynq_pri/zynq_study/DDS_test/alg/squ_wave.coe
add_files c:/code/zynq_pri/zynq_study/DDS_test/alg/sin_wave.coe
read_verilog -library xil_defaultlib C:/code/zynq_pri/zynq_study/DDS_test/rtl/src/DDS_test.v
read_ip -quiet c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_triangular/rom_triangular.xci
set_property used_in_implementation false [get_files -all c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_triangular/rom_triangular_ooc.xdc]

read_ip -quiet c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_square/rom_square.xci
set_property used_in_implementation false [get_files -all c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_square/rom_square_ooc.xdc]

read_ip -quiet c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_sine/rom_sine.xci
set_property used_in_implementation false [get_files -all c:/code/zynq_pri/zynq_study/DDS_test/rtl/syn/DDS_test/DDS_test.srcs/sources_1/ip/rom_sine/rom_sine_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top DDS_test -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DDS_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DDS_test_utilization_synth.rpt -pb DDS_test_utilization_synth.pb"
